// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int i = 0;
		int big = 0;
		int small = 0;
		int min = 0;
		int max = 1;
		while(i < N) {
			double random = (Math.random() * (max - min));
			i++;
			if (random > 0.5) {
				big = big + 1;
			} else {
				small = small + 1;
			}		
		}
		System.out.println("> 0.5: " + big + " times");
		System.out.println("<= 0.5: " + small + " times");
		}
	}
